name: Test and Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      # Server
      - uses: actions/checkout@v2
        with:
          repository: "RPMTW/RPMTW-Server"
          path: ${{ github.workspace }}/server

      - name: Cache Dart
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/dart-sdk
          key: ${{ runner.os }}-dart-2.16.0-134.5.beta
      # https://dart.dev/get-dart/archive
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.16.1
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}/server
          dart pub get
          dart pub global activate coverage
          export PATH="$PATH":"$HOME/.pub-cache/bin"
      - name: Start MongoDB 5.0
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 5.0
      - name: Start RPMTW Server
        run: |
        cd ${{ github.workspace }}/server
        dart run bin/server.dart RPMTW_SERVER_TEST_MODE=TRUE

      # Client
      - name: Generate coverage report
        run: |
          chmod +x gradlew
          ./gradlew test
      - name: Upload test report
        uses: codecov/codecov-action@v2
        with:
          files: "build/coverage/coverage.xml"

  Test:
    strategy:
      matrix:
        java-version: [ "8","11","16","17" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'

      # Server
      - uses: actions/checkout@v2
        with:
          repository: "RPMTW/RPMTW-Server"
          path: ${{ github.workspace }}/server

      - name: Cache Dart
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/dart-sdk
          key: ${{ runner.os }}-dart-2.16.0-134.5.beta
      # https://dart.dev/get-dart/archive
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.16.1
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}/server
          dart pub get
          dart pub global activate coverage
          export PATH="$PATH":"$HOME/.pub-cache/bin"
      - name: Start MongoDB 5.0
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 5.0
      - name: Start RPMTW Server
        run: |
        cd ${{ github.workspace }}/server
        dart run bin/server.dart RPMTW_SERVER_TEST_MODE=TRUE

      # Client
      - name: Run tests
        run: |
          chmod +x gradlew
          ./gradlew test

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RPMTW-API-Client-Kotlin-Build.zip
          path: "build/libs"
